### ISSUE TITLE
Use JSON Schema to describe argument types

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#143]
Now that we allow any JSON structures, our existing YAML format is lacking, since we don't have a way to describe nested object types.

We probably don't want to invent this, since this is what JSON Schema already does. 

JSON Scheme can be represented as YAML, so we could embed JSON Schema directed in our YAML to describe argument types, including complex types. These schema elementents can be used directly when we generate JSON Schema for the SXL.

Example for M0019. The `arguments` field is json schema, and as shown you can use json schema mechanism to validate combinations of fields:

```yaml
      M0019:
        description: |-
          Force input.
          Force a given input (1-255) of the controllers general purpose I/O to either True or False. Can be used for all types of input where the traffic light controller must react to external control.
          Can be used for bus priority, coordination between traffic controllers, external control systems, and much more.
          Requires security code 2.
        from_version: 1.0.13
        arguments:
          type: object
          properties:
            status:
              type: boolean
              description: |
                False: Release input
                True: Force input
            securityCode:
              type: string
              description: Security code 2
            input:
              type: integer
              minimum: 1
              maximum: 255
              description: Number of Input
            inputValue:
              type: boolean
              description: |
                False: input forced to False
                True: input forced to True
          required:
            - status
            - securityCode
            - input
          allOf:
            - if:
                properties:
                  status:
                    const: true
              then:
                required: [inputValue]
            - if:
                properties:
                  status:
                    const: false
              then:
                not:
                  required: [inputValue]
        command: setInput
```

S0033 example with nested types (array of object):

```yaml
S0033:
  description: |-
    Signal Priority Status
    This status can be used to get updates about priority requests. For example, you can use it to know when priority requests are activated or cancelled.
    A list of priorities is returned, referred to by their request ids. The same request id can appear only once.
    All priorities are included in the list (not only the ones that have changed state since the last update). This is done regardless of whether the status is send in respond to a status request, or due to a status subscription, and also regardless of whether a status subscription uses an update interval, or send-on-change, or both.
    If you subscribe using an update interval, you’re not guaranteed to get all intermediate states. To guarantee that, send-on-change must be used when subscribing.
    To understand how this status relates to ETSI/J2735, please see the [wiki](https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/wiki/Signal-priority-and-ETSI-J2735).
    All priorities are send on every status update, regardless of whether an interval, or sendOnChange (or both) is used.
    When a priority reaches an end states (completed, timeout, rejected, cooldown or stale), it must be sent once on the next status update, then removed from the list.
    A request always starts in the ‘received’ state. The following table shows the possible state transitions:

    State      | Possible next states
    ---------- | -------------------------------------
    received   | queued, activated, rejected, cooldown
    queued     | activated, timeout
    activated  | completed, stale
    completed  |
    timeout    |
    rejected   |
    cooldown   |
    stale      |
  from_version: 1.1.0
  arguments:
    type: object
    properties:
      status:
        type: array
        description: JSON array of priority status items
        items:
          type: object
          properties:
            r:
              type: string
              description: ID of the priority request
            t:
              type: string
              format: date-time
              description: Timestamp, indicating when the priority last changed state.
            s:
              type: string
              description: Current status of the priority request
              enum:
                - received
                - queued
                - activated
                - completed
                - timeout
                - rejected
                - cooldown
                - stale
            e:
              type: integer
              minimum: 0
              maximum: 255
              description: |
                Estimated green extension provided by the priority, in seconds.
                Only used when state is ‘completed’.
            d:
              type: integer
              minimum: 0
              maximum: 255
              description: |
                Estimated red reduction provided by the priority, in seconds.
                Only used when state is ‘completed’.
          required:
            - r
            - t
            - s
    required:
      - status
S0033:
  description: |-
    Signal Priority Status
    This status can be used to get updates about priority requests. For example, you can use it to know when priority requests are activated or cancelled.
    A list of priorities is returned, referred to by their request ids. The same request id can appear only once.
    All priorities are included in the list (not only the ones that have changed state since the last update). This is done regardless of whether the status is send in respond to a status request, or due to a status subscription, and also regardless of whether a status subscription uses an update interval, or send-on-change, or both.
    If you subscribe using an update interval, you’re not guaranteed to get all intermediate states. To guarantee that, send-on-change must be used when subscribing.
    To understand how this status relates to ETSI/J2735, please see the [wiki](https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/wiki/Signal-priority-and-ETSI-J2735).
    All priorities are send on every status update, regardless of whether an interval, or sendOnChange (or both) is used.
    When a priority reaches an end states (completed, timeout, rejected, cooldown or stale), it must be sent once on the next status update, then removed from the list.
    A request always starts in the ‘received’ state. The following table shows the possible state transitions:

    State      | Possible next states
    ---------- | -------------------------------------
    received   | queued, activated, rejected, cooldown
    queued     | activated, timeout
    activated  | completed, stale
    completed  |
    timeout    |
    rejected   |
    cooldown   |
    stale      |
  from_version: 1.1.0
  arguments:
    type: object
    properties:
      status:
        type: array
        description: JSON array of priority status items
        items:
          type: object
          properties:
            r:
              type: string
              description: ID of the priority request
            t:
              type: string
              format: date-time
              description: Timestamp, indicating when the priority last changed state.
            s:
              type: string
              description: Current status of the priority request
              enum:
                - received
                - queued
                - activated
                - completed
                - timeout
                - rejected
                - cooldown
                - stale
            e:
              type: integer
              minimum: 0
              maximum: 255
              description: |
                Estimated green extension provided by the priority, in seconds.
                Only used when state is ‘completed’.
            d:
              type: integer
              minimum: 0
              maximum: 255
              description: |
                Estimated red reduction provided by the priority, in seconds.
                Only used when state is ‘completed’.
          required:
            - r
            - t
            - s
    required:
      - status
```
