### ISSUE TITLE
More readable YAML format for describing an SXL

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#2]
The JSON Schema format is great because it can be used to automatically validate RSMP messages.

However, it's not that readable. As an example consider the schema for the traffic light controller S0001 status message:

```json
{
  "allOf" : [
    { "properties" : { 
      "description": "Signal group status",
      "n" : { "enum" : ["signalgroupstatus", "cyclecounter", "basecyclecounter", "stage"] }
    }},
    {
      "if" : { "required" : ["n"], "properties" : { "n" : { "const" : "signalgroupstatus" }}},
      "then" : { "properties" : {
        "v" : {
          "$description": "Signal group status as text field",
          "type" : "string"
	  }
      }}
    },
    {
      "if" : { "required" : ["n"], "properties" : { "n" : { "const" : "cyclecounter" }}},
      "then" : { "properties" : {
        "v" : {
          "$description": "Cycle counter",
          "$ref": "../../core/definitions.json#/integer"
	  }
      }}
    },
    {
      "if" : { "required" : ["n"], "properties" : { "n" : { "const" : "basecyclecounter" }}},
      "then" : { "properties" : {
        "v" : {
          "$description": "Base cycle counter",
          "$ref": "../../core/definitions.json#/integer"
         }
      }}
    },
    {
      "if" : { "required" : ["n"], "properties" : { "n" : { "const" : "stage" }}},
      "then" : { "properties" : {
        "v" : {
          "$description": "Current stage (isolated)",
          "$ref": "../../core/definitions.json#/integer"
	  }
      }}
    }
  ]
}
```

JSON Schema can also be represented in YAML format, which is perhaps a bit easier to read, but not much:

```yaml
---
allOf:
- properties:
    description: Signal group status
    n:
      enum:
      - signalgroupstatus
      - cyclecounter
      - basecyclecounter
      - stage
- if:
    required:
    - n
    properties:
      n:
        const: signalgroupstatus
  then:
    properties:
      v:
        "$description": Signal group status as text field
        type: string
- if:
    required:
    - n
    properties:
      n:
        const: cyclecounter
  then:
    properties:
      v:
        "$description": Cycle counter
        "$ref": "../../core/definitions.json#/integer"
- if:
    required:
    - n
    properties:
      n:
        const: basecyclecounter
  then:
    properties:
      v:
        "$description": Base cycle counter
        "$ref": "../../core/definitions.json#/integer"
- if:
    required:
    - n
    properties:
      n:
        const: stage
  then:
    properties:
      v:
        "$description": Current stage (isolated)
        "$ref": "../../core/definitions.json#/integer"
```

There's still a lot of stuff that's not really about the SXL, but is required to construct the schema, like the if/then blocks.

I propose an intermediate YAML format, used to describe an SXL in the most straightforward way.
It's easily readable and can be versioned well (unlike excel sheets). The JSON Schema would then be rendered from this format.

```yaml
S0001: 
  description: Signal group status
  arguments:
    signalgroupstatus:
      description: Signal group status as text field
      type: string
    cyclecounter:
      description: Cycle counter
      type: integer
    basecyclecounter:
      description: Base cycle counter
      type: integer
    stage:
      description: Current stage (isolated)
      type: integer
```

This intermediate format is also easier to use to e.g. automatically test all messages in an SXL, since you don't have to deal with the if/then/allOff stuff when you read it. Importing YAML into Ruby (and other languages) is very easy.

YAML also supports multiline text:

```yaml
description: >
  Options:
  1: Activate
  2: Deactivate
```

ping @otterdahl

**Comment by otterdahl** [comment]
It makes sense. An easy readable format is preferred

**Comment by emiltin** [comment]
Pushed the branch used to import from markdown and generate json schema. Could be modified to generate yaml, however any later manual changes to the json schema would be lost.
Perhaps a better way is to import the json schema and generate yaml and keep that as the base format. Then later we can  reimport from yaml and generate the json schema.

**Comment by emiltin** [comment]
I've created an importer that converts status messages from the json schema to YAML.
Here's the output: https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2

The idea is to keep and maintain this format as the source, and generate json, csv, etc from this going forward.

Notes:
- For text containing newlines, literal block format is used, denoted by a '|' character
- Show enum list use flow format, eg. [yes,no,maybe]
- \<br\> was converted to newline
- Strings containing ':' colon must use literal block format (alternative would be quoting)
- '[' and ']' were converted to < and >, since '[' is reserved for arrays in yaml. Alternative would be to use quoting or literal block format. If we keep <> we should use this in the docs as well.

**Comment by emiltin** [comment]
Do we want statuses, commands and alarms in a single yaml file, or do we want to split it into multiple files? I lean towards a single file

**Comment by emiltin** [comment]
In the example yaml output, the descriptions are often the last item. I've changed this so they're always comes first, as this is easier to read.

**Comment by otterdahl** [comment]
It's a good start. I also think that it it would be best to fit everything in a single yaml file.

Please note that the example is missing **ObjectType** *. For instance, **S0025** has the **ObjectType** _"Signal group"_.

**Comment by emiltin** [comment]
Good point with the object type. The reason it's not in the yaml is that it's not currently in the json schema either. The yaml is converted from the json schema.

What does it mean that the obecttype is e.g SIgnalGroup? That you can only requst that status for signal groups? If so it seems it's not in the json message and thus nothing we can validate with the schema. But of course it should be in the yaml. I might just add it manually once the conversion is otherwise ok.

**Comment by emiltin** [comment]
I'm considering moving descriptions of values (enums) from the description to a separate hash. So instead of:
```yaml
        description: |
          Type of logic error
          always_off: no detection during prefined max time
          always on: detection constantly on during predefined max time
          intermittent: intermittent logic fault (flutter)
        type: string
        values: [always_off, always_on, intermittent]
```

it would be:
```yaml
        description: |
          Type of logic error
        type: string
        values:
          always_off: no detection during prefined max time
          always on: detection constantly on during predefined max time
          intermittent: intermittent logic fault (flutter)
```
    
```

**Comment by emiltin** [comment]
updated draft with statuses, commands and alarms:
https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2

**Comment by otterdahl** [comment]
> I'm considering moving descriptions of values (enums) from the description to a separate hash.

I like the idea. And I suppose it is backwards compatible as well.

> What does it mean that the obecttype is e.g SIgnalGroup? That you can only requst that status for signal groups?

Correct

> updated draft with statuses, commands and alarms:
> https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2

Good progress!

I've been working on a tool which converts yaml back to excel - to be sure we're not missing something from the SXL. Currently the following is missing from the YAML file:

- No definition of ObjectType, e.g. Traffic Light Controller, Signal Group, etc.
- No definitions of Objects (Components), e.g. the number of signal groups, detector logics which a specific TLC have. (This type of data has was deliberately absent from the md/rst version of the SXL, because data of a specific TLC isn't needed for viewing online). But the SXL is commonly used to describe the configuration of the physical road side equipment
- Command is missing _command_ (or cO). See https://rsmp-nordic.github.io/rsmp_core/applicability/basic_structure.html#command-messages
- Alarm is missing priority and category
- Aggregated status is missing
- Version information is missing, etc. Constructor, SXL revision, created date and so on.
-  There can be several alarms/status/command's with the same Id (See screenshot below from the RSMP simulator) - but with different object types. The object_type needs to be on a deeper level


Example of YAML with "Traffic Light Controller" between **statuses** and **S0009**
```
statuses:
  Traffic Light Controller:
    S0009:
      description: Fixed time control
      object_type: Traffic Controller
      arguments:
        intersection:
          description: |
            0: Not applicable (only one intersection exists or applicable for all intersection of the traffic controller)
            Other value: Intersection number
          type: integer
        status:
          description: |
            False:  Fixed time control inactive
            True:  Fixed time control active
          type: boolean
```

Screenshot showing multiple A0001 with diffrent object types:

![1](https://user-images.githubusercontent.com/2820709/82670846-3045af00-9c3e-11ea-9cc1-3ce499a4ed84.png)

**Comment by emiltin** [comment]
Good input.

I really think we should keep the SXL general and move documentation of individual TCL devices to a separate template that can be filled out for each device. That template can still be defined in yaml and exported to json schema for validation if we wish. The device documentation should just specify what SXL and version it's using instead of copying it.

The screenshot above shows different A0001 messages defined for Traffic Controller and Signal Group. But I don't see this reflected in the current documenation at https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/master/sxl_traffic_controller.md#alarms? I see alarms for different object types but no overlapping alarm codes.

I thought agggregated status was defined in core and was the same for all types of equipment. But it's defined for each type of grouped object? (for a TLC that would be only Traffic Controller)

**Comment by emiltin** [comment]
Suggestion for organising yamls for the general sxl, and for device configurations:
The SXL is organized by objects types first. Grouped objecst include aggregated status. Each object type then includes statuses, commands and alarms where relevant:

```yaml
---
id: traffic_light_controller 
description: SXL for traffic light controllers
version: 1.0.16
date: 2020-10-10
objects:
  traffic_controller:
    aggregated_status:
      1: Local mode
      2: No communications
    statuses:
      S0001:
    commands:
      M0001:
    alarms:
      A0001:
  signal_group:
    statuses:
      S0001:
    alarms:
      A0001:
  detector_logic:
    statuses:
      S0001:
```

The config for a single device is also organised by object type, and for each lists the objects defined, e.g. the signal groups and their names. It could potentially later be expaned to include the content of signal programs. etc
 
```yaml
---
id: AG10.40
description: Configuration for AG 10.45 Storegade
version: 1
date: 2020-10-10
objects:
  traffic_controller:
    TC:
  signal_group:
    SG01:
    SG02:
  detector_logic:
    DL1:
    DL2:
```

**Comment by emiltin** [comment]
cO doesn't seem to have use real use, since it's the same for all command names. E.g M001 has setValue for all command names, which btw seems quite confusing. Why include 'setValue' in all M0001 commands?

**Comment by emiltin** [comment]
updated draft:
https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2

**Comment by emiltin** [comment]
The aggregated status is also missing because it's not curently in the json schema. It's pretty simple to add it manually once we're satisfied with the json->yaml import

**Comment by otterdahl** [comment]
> cO doesn't seem to have any real use, since it's the same for all command names. E.g M001 has setValue for all command names, which btw seems quite confusing. Why include 'setValue' in all M0001 commands?

Back in 2012 we had a discussion about **command (cO)** being redundant. This was our motivation to keep cO.

In theory; **command (cO)** could be treated as optional since both **commandCodeId (cCi)** and **name (n)** provide all information needed to uniquely identify a value. However; the RSMP protocol is designed to primarily be non-vendor specific, and therefore the manufacture specific command codes is simply missing by default. With **command (cO)** we at least have the ability to preserve manufacture specific command codes between different systems (compare this with e.g. **externalAlarmCodeId**) and therefore simplify the adoption of RSMP without the need to translate command codes at different system levels.

It also makes it more transparent and helps with debugging. Even though **command** is not used like that in the current version of the SXL; this provides the flexibility for this usage in the future. The reason for sending **command (co)** in each and every argument is due to flexibility reasons; as we can't know for sure if there will a perfect correlation between **commandCodeId**, **name**, and **command** for each situation where this could be applicable (one command may have many arguments; and several commands could theoretically be included within a single **commandCodeId**). One could still argue that command should be optional, but we don't consider the given reasons strong enough to change the RSMP specification in this regard. Perhaps in a future version of RSMP. The extra data that needs to be sent due to the addition of 'command' is considered to be minimal since commands are not sent that often.

**Comment by otterdahl** [comment]
> The screenshot above shows different A0001 messages defined for Traffic Controller and Signal Group. But I don't see this reflected in the current documenation at https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/blob/master/sxl_traffic_controller.md#alarms? I see alarms for different object types but no overlapping alarm codes.

Correct. This is not documented and I have never seen any SXL which actually have multiple command/status with the same id (but with different object types). It probably a good idea to avoid this since it may cause confusion. But I have noticed that the RSMP simulator supports this, but it may be unintended. I still thinks it is a good idea to have object_type on a deeper level to avoid any potential problems, in case someone actually have done this. I see the draft is already updated

**Comment by otterdahl** [comment]
> I thought agggregated status was defined in core and was the same for all types of equipment. But it's defined for each type of grouped object? (for a TLC that would be only Traffic Controller)

The eight status bits and their generic descriptions are defined in core. But the SXL also defines descriptions for how to interpret the statuses for a specific type of equipment. See the _comment_ column at table 2.4 https://otterdahl.org/rsmp/sxl_traffic_light_controller.html#aggregated-status 

The aggregated status also contain **functionalPosition (fP)** and **functionalState (fS)** which are enums containing the possible positions or states which the site can enter. See https://github.com/rsmp-nordic/rsmp_core/issues/45

**Comment by otterdahl** [comment]
> Suggestion for organising yamls for the general sxl, and for device configurations:

Yes. I think this is a good approach

**Comment by otterdahl** [comment]
> The config for a single device is also organised by object type, and for each lists the objects defined, e.g. the signal groups and their names. It could potentially later be expaned to include the content of signal programs. etc
> 
> ```yaml
> ---
> id: AG10.40
> description: Configuration for AG 10.45 Storegade
> version: 1
> date: 2020-10-10
> objects:
>   traffic_controller:
>     TC:
>   signal_group:
>     SG01:
>     SG02:
>   detector_logic:
>     DL1:
>     DL2:
> ```

It's a good start. What also would be good is to have is **siteId** to be between **objects**: and the components (.e.g traffic controller, signal group, detector_logic). It is also good to have an id and description of the siteId. The reason is that a single RSMP connection can support multiple siteId at once. Each with a different set of components. This not used for traffic signals of course, but it is used in other types of equipment.

Updated suggestion:

```yaml
---
id: Traffic signals system A
description: Name of installation
version: 1
date: 2020-10-10
site:
  id: AG10.40
  description: Configuration for AG 10.40 Storegade
  objects:
    traffic_controller:
      TLC: AA+BBCCC=DDDEEFF1
  signal_group:
     SG01: AA+BBCCC=DDDEEFF1
     SG02: AA+BBCCC=DDDEEFF2
     SG03: AA+BBCCC=DDDEEFF3
   detector_logic:
     DL1: AA+BBCCC=DDDDLAA1
site:
  id: AG10.41
  description: Configuration for AG 10.41 Storegade
  objects:
    traffic_controller:
      TLC: AA+BBCCC=DDDEEFF2
  signal_group:
     SG01: AA+BBCCC=1234EFF1
     SG02: AA+BBCCC=1234EFF1
   detector_logic:
     DL1: AA+BBCCC=1234LAA1
     DL2: AA+BBCCC=1234LAA2
```

The example above assumes that we've removed NTSObjectId and externalNtsId as discussed in https://github.com/rsmp-nordic/rsmp_core/issues/9

**Comment by otterdahl** [comment]
> updated draft:
> https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2
> 
> Currently all statues/commands/alarms are in the traffic_controller object, some needs to be split out to signal_group and detector_logic

Good update. I see **cO** was added and **object_type** is on a deeper level
The following still remains

- ObjectTypes are still missing. Each object type have a description
- Aggregated status is missing. (discussed in an earlier post)
- Alarms are missing category and priority

**Comment by emiltin** [comment]
cO: Thank you for explanation. It does not make much sense to me, we've been sending cO values since 2012 for no practical reason. But I can open a separete issue for that if needed.

Multiple commands with the same id: What' confusing in case we allow it, is that the tlc sxl currently avoids it. So you don't expect it, at least that why it surprised me. Existing rsmp implementations might make similar assumptions and might break when faced with two different S0001 status for different object types.

On the other hand, there might be some obscure SXL that becomes invalid if we require all ids to be unique.

But we can leave the organization of the yaml. Is the current structure what you mean when you write 'object type on a deeper level? I would say it's on a high level...?

You can't have two 'site' keys in a hash. I suggest a slight redesign:
```yaml
---
id: Traffic signals system A
description: Name of installation
version: 1
date: 2020-10-10
sites:
  AG10.40:
    description: Configuration for AG 10.40 Storegade
    objects:
      traffic_controller:
        TLC: AA+BBCCC=DDDEEFF1
    signal_group:
       SG01: AA+BBCCC=DDDEEFF1
       SG02: AA+BBCCC=DDDEEFF2
       SG03: AA+BBCCC=DDDEEFF3
     detector_logic:
       DL1: AA+BBCCC=DDDDLAA1
  AG10.41:
    description: Configuration for AG 10.41 Storegade
    objects:
      traffic_controller:
        TLC: AA+BBCCC=DDDEEFF2
    signal_group:
       SG01: AA+BBCCC=1234EFF1
       SG02: AA+BBCCC=1234EFF1
     detector_logic:
       DL1: AA+BBCCC=1234LAA1
       DL2: AA+BBCCC=1234LAA2
```

**Comment by emiltin** [comment]
> ObjectTypes are still missing. Each object type have a description

We can add a description here

```yaml
objects:
  traffic_controller:
    description: The main controller # dscribe this object type
    statuses:
      S0001:
        description: Signal group status
        arguments:
          ...
```

Aggregated status will be added by hand, since it's not currently in the json.

Alarms are missing category and priority: That are not currently in the json, so we will have to add them manually, or import from excel/csv. Manually might be easier.

**Comment by emiltin** [comment]
Updated draft: https://gist.github.com/emiltin/a4fe779f689bef76406607c76851b1c2

I have a slight concern that the yaml is getting pretty long and some content is 5-6 levels deep. Still pretty readable though, especially since you can view it with syntax highlighting with common editors like SublimeText, or online tools.

It we want we can add a json schema for the yaml files, to validate the format.

**Comment by otterdahl** [comment]
> But we can leave the organization of the yaml. Is the current structure what you mean when you write 'object type on a deeper level? I would say it's on a high level...?

Correct. My mistake

**Comment by otterdahl** [comment]
> > ObjectTypes are still missing. Each object type have a description
> 
> We can add a description here
> 
> ```yaml
> objects:
>   traffic_controller:
>     description: The main controller # dscribe this object type
>     statuses:
>       S0001:
>         description: Signal group status
>         arguments:
>           ...
> ```

The problem with this approach is that alarms/commands/statuses may have different **object types**. You'd most likely want to read them i sequential order. See [the alarm table](https://otterdahl.org/rsmp/sxl_traffic_light_controller.html#alarms)

What about this format instead? This would define the object_types separately
```yaml
objects_types:
  traffic_controller:
    description: The main controller # describe this object type
  signal_group:
    description: Signal group
  detector_logic:
    description: Detector logic
statuses:
  S0001:
    object_type: traffic_controller
    description: Signal group status
    arguments:
          ...
  S0025:
    object_type: signal_group
    description: Time-of-Green / Time-of-Red
    arguments:
          ...
 ```

**Comment by emiltin** [comment]
If we allow multiple statuses/alarms/commands with the same id with different object type, then example 2 does not work, because a hash cannot have two items with the same key. If would work if we require all ids to be unique.

In the first example, traffic_controller is the object type, so each object type has it's own set of statuses/alarms/commands:

```yaml
objects:
  traffic_controller:
    description: The main controller
    statuses:
      S0001:
        description: Signal group status for tlc
  signal_group:
    description: A signal group
    statuses:
      S0001:
        description: Signal group status for tlc
 ```

But as you say, items are sorted by object type rather than id.

The basic problem is that the design is a bit messy. Having a list sorted by id, and also have multiple items with the same id is akward. We're sitting between two chairs: The tlc sxl uses unique ids, and the documentation sorts by id, but we still want to allow multiple items with the same id.

**Comment by otterdahl** [comment]
I see. I that case, I would prefer that we simply drop support for multiple statuses/alarms/commands with the same id with different object type.

**Comment by otterdahl** [comment]
> I see. I that case, I would prefer that we simply drop support for multiple statuses/alarms/commands with the same id with different object type.

If this makes it too messy/akward (especially ```object_type: traffic_controller``` in my suggestion), then I suppose it is OK to sort by object_type instead.

**Comment by emiltin** [comment]
After pondering this, I suggest we require all ids to be unique across object types. We structure the yaml by id and include object_type in each item, as you suggested above (and which was the initial draft also):

```yaml
objects:
  traffic_controller:
    description: The main controller # describe this object type
  signal_group:
    description: Signal group
  detector_logic:
    description: Detector logic
statuses:
  S0001:
    object: traffic_controller
    description: Signal group status
    arguments:
          ...
  S0025:
    object: signal_group
    description: Time-of-Green / Time-of-Red
    arguments:
```

I think this is the clearest, easier to read and easier to validate with a json schema. Having 'object' (or 'object_type') is not a problem, we also have description, argument, etc. in each item.
