### ISSUE TITLE
SXL: functional_position and functional_state need be treated as arrays

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_schema#27]
In the [SXL 1.1](https://github.com/rsmp-nordic/rsmp_schema/blob/master/schemas/tlc/1.1/sxl.yaml) TLC the fields `functional_position` and `functional_state` are treated as string:

```yaml
    functional_position: not used (set to null)
    functional_state: not used (set to null)
```
However, they need to be treated as arrays, because functional_position and functional_state - if used - defines a list of possible values that is can be.

Example:
![bild](https://user-images.githubusercontent.com/2820709/201765383-6bd8a2ba-b4c0-46e9-b98a-3f03521f7104.png)

which can be expressed like this in yaml:
```yaml
functional_position: 
       olycka: ''
       gaslarm: ''
       släckt: ''
       ojämn_väg: ''
       slirig_vägbana: ''
       vägarbete_höger_körfält: ''
       vägarbete_vänster_körfält: ''
       kö: ''
       annan_fara: ''
       sidvind_från_höger: ''
       sidvind_från_vänster: ''
```

So far, I've used a separate field for the description in the TLC SXL:
```yaml
    functional_position:
    functional_state:
    aggregated_status_description: functionalPosition and functionalState not used (set to null)
```

**Comment by emiltin** [comment]
Do you mean it's an array, but the values are limited to enum values? (Multi enum)

**Comment by otterdahl** [comment]
> Do you mean it's an array, but the values are limited to enum values? (Multi enum)

Yes

**Comment by emiltin** [comment]
ok. yes we should probably add that as a type in our yaml (and related converters)

**Comment by emiltin** [comment]
The existingstring_list type allows a list of strings. if combined with specifying values, it's close to what we want.

But there are currently no way to require that no items are duplicated. We could either introduce new types:

```yaml
functional_position: 
  description: Indicates expectional conditions.
  type: string_multi_enum
  values:
    acciddent: An accident has happened.
    queue: Vehicles a queueing
    wind: Dangerious wind conditions.
```

Or use a separete option to require unique items, which I think is my favorite:

```yaml
functional_position: 
  description: Indicates expectional conditions at the site.
  type: string_list
  unique_items: true
  values:
    acciddent: An accident has happened.
    queue: Vehicles a queueing
    wind: Dangerious wind conditions.
```

See e.g. https://jsonforms.io/docs/multiple-choice/#multi-select for how others handle multi enums.
