### ISSUE TITLE
SXL: several statuses not marked as deprecated or reserved for future use

### ISSUE THREAD

**Issue by otterdahl** [rsmp-nordic/rsmp_schema#28]
There are several cases where statuses is not marked as deprecated or reserved for future use

The following arguments were marked as "deprecated" in 1.1: https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/issues/74
- S0003 'extendedinputstatus'
- S0004 'extendedoutputstatus'

They were added a long time ago but never got used.
Here is an example diff from the SXL which I've used. I've added ``Deprecated``  at the top. 

```diff
             description: |-
-              ``Deprecated`` Extended input status as text field
-              
-              Each character represent the state of the extended input status in consecutive order.
-              0 = Input is not active
-              1 = Input is active
-              - = Input is undefined/does not exist
+              Extended input status as text field
+              Each character represent the state of the detector logic in consecutive order.
+              0 : Input is not active
+              1 : Input is active
+              - : Input is undefined/does not exist
```

The following statuses were marked as "reserved" in 1.1: https://github.com/rsmp-nordic/rsmp_sxl_traffic_lights/commit/d13068312c899440222e201cb11d3c47d1358f01
- M0010
- M0011
- M0012

They were all added as part of coordination support, but never got any actual use. No one are currently using them, but can potentially be interesting to use in the future.

As you can se here https://rsmp-nordic.org/rsmp_specifications/rsmp_sxl_traffic_lights/1.1/sxl_traffic_light_controller.html#commands, they are complete removed and replaced with ``Reserved``.

Should we add a field in the YAML SXL to say "deprecated" or "reserved"?

For instance:
```yaml
extendedoutputstatus:
            type: string
            deprecated: true
            description: |-
              Output status as text field
              
              Each character represent the state of the exteded output status in consecutive order.
              0 = Output is not active
              1 = Output is active
              - = Output is undefined/does not exist
```
or

```yaml
M0010:
        description: |-
          Start of signal group. Orders a signal group to green.
          Although this command is intended to be used with coordination it is not actually specified to be used for this yet. It is reserved in the SXL for possible future use.
          Intended for use with coordination of signaling systems where a traffic light controller communicates with neighboring controllers. Only used when a primary controller orders signal group of other controller to green or red (Coordination with external control bits).
          Requires security code 2
        reserved: true
        arguments:
          status:
            type: boolean
            description: |-
              False: No command (default)
              True: Order a signal group to green
          securityCode:
            type: string
            description: Security code 2
        command: setStart

```
