### ISSUE TITLE
Multiple object types in an SXL?

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#60]
An SXL can historically contain mulitple object types, each with different agggregated statuses, alarms, statues, etc. This is reflected in the structure of our YAML:

```yaml
---
meta:
  name: tlc
  description: Traffic Light Controllers
  version: 1.1
objects:                               # this is an array of object types
  Traffic Light Controller:            # this is the first (and only) item
    description:
    aggregated_status:
      1:
        title: Local mode
...
```

But it's not currently used when generating json scheme, because the only SXL we have to work with is the one for TLCs and it only has a single object type.

Do we need multiple object types in a single SXL/YAML? Or could we simplify things?
