### ISSUE TITLE
don't use enums for user arg in S0091 and S0092

### ISSUE THREAD

**Issue by emiltin** [rsmp-nordic/rsmp_schema#7]
don't use enums for the 'user' argument in S0091 and S0092, as the username depends on settings in the TLC and therefore cannot be verified by the json schema

https://rsmp-nordic.github.io/rsmp_sxl_traffic_lights/sxl_traffic_light_controller.html#s0091

**Comment by emiltin** [comment]
not relevant any longer in 1.1, as we're not using enum values [0,1,2].
need to check for 1.0.15 and older

**Comment by emiltin** [comment]
for sxl <= 1.0.15, the user attribute be eiter 'nobody' and a user name, so in effect any value except an enmpty string.

this is already reflected in the sxl.yaml for 1.0.15 and earlier:

```yaml
          user:
            description: |-
              nobody: No one logged in
              <username>: User currently logged in
            type: string
```

closing, no more to do
